active-opacity = 0.8
inactive-opacity = 0.5
frame-opacity = 0.7
corner-radius = 12;
opacity-rule = [
	"100:class_g *?= 'Rofi'",
	"100:class_g *?= 'Librewolf'",
  "100:class_g *?= 'Libreoffice'",
  "100:class_g *?= 'Chromium'",
  "100:class_g *?= 'Brave-Browser'",
  "100:class_g *?= 'Wireshark'",
  "100:class_g *?= 'Opera gx'"
];
