font_family FiraCodeNerdFontRegular
font_size 16

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
tab_bar_style powerline
inactive_tab_background #e06c75
active_tab_background #98c379

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
